name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Paquete para manejar solicitudes HTTP (versión compatible)
  http: ^1.2.2

  # Paquete opcional para formateo de datos
  intl: ^0.18.0

  # Paquete para usar íconos de estilo iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
